### ISSUE TITLE
Allow for more complex Repeater PageViews

### ISSUE THREAD

**Issue by allejo** [stakx-io/stakx#100]
| Description | Value |
| ------ | ----- |
| Status | Draft |
| Target | 0.2.1 |
| BC | Yes |

This is a proposal for extending the Repeater PageView behavior to allow for more complex nesting of permalinks. This feature would also be the foundation for supporting pagination at stakx's core.

## Summary

```yaml
---
projects:
  - bzflag:
      _projects: "%category"
      category:
        - null
        - plug-ins
        - projects
  - jekyll:
      _projects: "%category"
      category:
        - projects
        - themes
  - libraries
  - stakx
  - web-design
permalink: /projects/%projects/
---
```

The following Front Matter would generate the following permalinks:

- `/projects/bzflag/`
- `/projects/bzflag/plug-ins/`
- `/projects/bzflag/projects/`
- `/projects/jekyll/projects/`
- `/projects/jekyll/themes/`
- `/projects/libraries/`
- `/projects/stakx/`
- `/projects/web-design/`

The following variables would be available in Twig:

- `this.iterators.projects` = `bzflag`
- `this.iterators.projects.iterators.category` = `null`
- `this.iterators.projects.iterators.category` = `plug-ins`
- `this.iterators.projects.iterators.category` = `projects`

## Detailed Description

At the moment, value expansion only works with an array of strings. This behavior would allow for value expansion to work with associative arrays that allow for further scoped value expansion. When value expansion reaches the "bzflag" value, it will take the value `_projects` and append to the key of this associative array (i.e. `bzflag`) and build the permalink off of that. The underscore is the special symbol that will tell stakx to treat it specially.

At this point, we'll have the permalink of `/projects/bzflag/%category` and because of the scoping, it will then proceed to expand the values of this permalink with the values of `projects[0].bzflag.category` and generate three permalinks.

- `/projects/bzflag/`
- `/projects/bzflag/plug-ins/`
- `/projects/bzflag/projects/`
