### ISSUE TITLE
FrontMatter Script Specification

### ISSUE THREAD

**Issue by allejo** [stakx-io/stakx#2]
> **Heads Up!** This is just a thought. Whether or not it is to be implemented is still to be determined.

I'll open this issue for an idea I would like to experiment with for the next major release: FrontMatter Script (FScript, FS#, YamlScript). The name is still to be determined; name suggestions are welcome.

## Concerns

- Are there any examples of where this sort of functionality will be useful?
- Is this just an unnecessary complexity that will be introduced?
- What justifies something being added to this language? When will it stop?
- How much of this can be achieved with Twig?

## Math

```yaml
var_x: 10
var_y: 5
sum: %{var_x + var_y} # 15
diff: %{var_x - var_y} #5
product: %{var_x * var_y} # 50
quotient: %{var_x / var_y} # 2
```

## List Manipulation

```yaml
sample_list:
    - Toast
    - Bacon

new_list: %sample_list + 'Apple' # Toast, Bacon, Apple
```

## Ternary Statements

```yaml
toast_good: true
statement: (%toast_good) ? 'Toast' : 'Bacon' # Toast
```
