### ISSUE TITLE
Use dot syntax for Twig filters: select, where, group, order

### ISSUE THREAD

**Issue by allejo** [stakx-io/stakx#58]
For Front Matter like the following:

```yaml
---
category:
  name: eBay
  order: 1
---
```

Allow filters to use a dot syntax to go into arrays in Front Matter. For example:

```twig
{% set categories = collections.posts | order('category.order') %}
```

Twig filters that should support this:

- select
- group
- order
- where
