### ISSUE TITLE
Let 'url' function support Repeater PageViews

### ISSUE THREAD

**Issue by allejo** [stakx-io/stakx#77]
Static PageViews have the ability to be linked directly and dynamic PageViews have ContentItems or DataItems that can be linked directly through the `url()` function. However, the repeater PageView has no way of linking to it without manually building the URL.

Since `title` is a special FM key, let's apply that to create named Repeater PageViews available in a global `repeaters` template variable.

Given I have a usage example like so:

```twig
{{ url(repeaters['Repeater PageView Title'], params={
    category: 'blogging',
}) }}
```

It'd link to the repeater PageView that has the following FM:

```yaml
title: Repeater PageView Title
categories:
  - blogging
  - uncategorized
permalink: /blog/categories/%categories/
```
