### ISSUE TITLE
Allow 'url' filter to accept external URLs

### ISSUE THREAD

**Issue by allejo** [stakx-io/stakx#95]
The `url` filter is the standard way of creating links to internal stakx documents. However, they may be times where it references external URLs.

```yaml
jumbotron:
    image: https://placehold.it/1920x500
    alt: ~
```

```twig
<img src="{{ url(this.jumbotron.image) }}"
     alt="{{ this.jumbotron.alt }}"
     class="landing-jumbotron__image"
>
```

Given the above example, the `url()` filter will return

```
/https://placehold.it/1920x500
```

Which breaks the image. When a string is feed into the function and contains `://`, then it should return the value as is.
