### ISSUE TITLE
Generated routes with slashes as parameters don't work in serve

### ISSUE THREAD

**Issue by allejo** [stakx-io/stakx#98]
Given a Dynamic PageView with the following Front Matter:

e.g. [bzflag.org:_pages/documentation/show.html.twig](https://github.com/BZFlag-Dev/bzflag.org/blob/517a91fd3a1dee886a057afd1050be8878b19ff2/_pages/documentation/show.html.twig#L5)

```yaml
---
collection: user_documentation
permalink: /documentation/%docpath/
---
```

And a collection item with the following Front Matter:

e.g. [bzflag.org:_documentation/developer/pages/compiling-on-windows.md](https://github.com/BZFlag-Dev/bzflag.org/blob/master/_documentation/developer/pages/compiling-on-windows.md)

```yaml
---
title: Compiling on Windows
docpath: compiling/windows
---
```

The `build` command works as correctly forming a `/documentation/compiling/windows/` permalink when writing files. However, the current router we're using for the dev server does not support having parameters with slashes in them. This results in a 404 when trying to access this page while using `serve`.
